---
secrets_file: ./.secrets.yml

userdata:
  app:
    env: production
    port: 7788
    home: /app
    cache_path: /app/public/images

project:
  name: image-scaler
  description: Scales images dynamically

stacks:
- name: image-scaler
  description: Image Scaler App
  units:
    - name: app
      version: 1.0.0
      dockerfile: Dockerfile

      pre_build_scripts:
        - ./scripts/bundle.sh
      ports:
        - "{{ userdata.app.port }}:{{ userdata.app.port }}"
      volumes:
        - /data/image-scaler:/app/public
      env:
        - PORT={{ userdata.app.port }}
        - ENV={{ userdata.app.env }}
        - APP_CACHE_PATH={{ userdata.app.cache_path }}
        - IMAGE_SCALER_API_KEYS={{ secrets.image_scaler.api_keys | join:',' }}
