---
docker:
  host: unix:///var/run/docker.sock

userdata:
  app:
    port: 7788

project:
  name: image-scaler
  description: Scales images dynamically

stacks:
- name: image-scaler
  description: Image Scaler App
  units:
    - name: app
      version: 1.0.0
      dockerfile: Dockerfile

      pre_build_scripts:
        - ./scripts/bundle.sh
      ports:
        - "{{ userdata.app.port }}:{{ userdata.app.port }}"
      volumes:
        - /data/image-scaler:/app/public
      env:
        - PORT={{ userdata.app.port }}
        - ENV=production
